name: Build EXE for Windows

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        architecture: 'x86'

    - name: Install Dependencies
      run: pip install pyinstaller customtkinter

    - name: Build EXE
      # السطر أدناه مهم جداً لدمج التصميم العصري داخل البرنامج
      run: pyinstaller --noconsole --onefile --collect-all customtkinter app.py

    - name: Upload EXE File
      uses: actions/upload-artifact@v4
      with:
        name: Excel-Unlocker-Pro
        path: dist/app.exe
